In [2]:
import numpy as np

arr = np.ones((4, 3), dtype="int")
print(arr)
print(arr.shape)
print(arr.dtype)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
(4, 3)
int64


In [4]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr2 = np.arange(1, 10)
print(arr2)

[1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
import numpy as np
arr1 = np.arange(100)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
